### ISSUE TITLE
纯vue3中如何使用？好像没有发布vue3版本到npm仓库中

### ISSUE THREAD

**Issue by wuyezhong** [novlan1/press-ui#2]
纯vue3中如何使用？好像没有发布vue3版本到npm仓库中

**Comment by novlan1** [comment]
可以用这个包 press-ui-vue3
可以参考这里 https://h5.igame.qq.com/pmd-mobile.support.press-ui.press-ui/quickstart.html#_4-%E6%99%AE%E9%80%9A-vue3-%E9%A1%B9%E7%9B%AE
