### ISSUE TITLE
在vue-cli创建的uniapp小程序项目中使用，为何没有样式效果？

### ISSUE THREAD

**Issue by shirley1200** [novlan1/press-ui#4]
根据使用流程走的

**Comment by novlan1** [comment]
什么技术栈，给下最小可复现代码，或者参考示例项目





------------------ 原始邮件 ------------------
发件人: shirley1200 ***@***.***&gt;
发送时间: 2024年7月10日 18:11
收件人: novlan1/press-ui ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [novlan1/press-ui] 在vue-cli创建的uniapp小程序项目中使用，为何没有样式效果？ (Issue #4)
