### ISSUE TITLE
使用正常但是控制台有警告

### ISSUE THREAD

**Issue by xutao-o** [novlan1/press-ui#5]
使用正常但是控制台有警告， 使用脚手架安装的vite/vue3的uniapp项目

![image](https://github.com/user-attachments/assets/c90a1608-1ea0-4af0-bd97-51d921f6f0c8)

press-button.vue:260 [Vue warn]: Failed to resolve component: Button
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
 at <PressButton>

**Comment by xutao-o** [comment]
https://uniapp.dcloud.net.cn/quickstart-cli.html#install-vue-cli

vite的uniapp项目
npx degit dcloudio/uni-preset-vue#vite my-vue3-project

**Comment by novlan1** [comment]
可以先通过下面的方式进行去除，下个版本优化下 @xutao-o 


`
// vite.config.ts
const CUSTOM_ELEMENTS = [
  'Button',
  'Input',
  'Textarea',
];


// ...

 plugins: [
    uni({
        vueOptions: {
          template: {
            compilerOptions: {
              isCustomElement: (tag: string) => CUSTOM_ELEMENTS.includes(tag)
              ,
            },
          },
        },
      }),
]
// ...
`

**Comment by novlan1** [comment]
v2.1.22 已解决
